"""Moving is_active to user table

Revision ID: 8233ded920ca
Revises: 7f30f9a30953
Create Date: 2022-06-09 16:31:44.974344

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "8233ded920ca"
down_revision = "7f30f9a30953"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("profiles", "is_active")
    op.add_column("users", sa.Column("is_active", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "is_active")
    op.add_column(
        "profiles",
        sa.Column(
            "is_active", sa.BOOLEAN(), autoincrement=False, nullable=True
        ),
    )
    # ### end Alembic commands ###
